import { readFileSync } from "node:fs";
const load=(p)=>JSON.parse(readFileSync(new URL(p,import.meta.url),"utf8"));
const catalog=load("../src/config/educativeProgramRelations.json"),artifact=load("../src/config/vocationalProgramProfiles.json"),lexicon=load("../src/config/vocationalConceptLexiconV2.json");
const ids=Object.keys(catalog.programs),profileIds=Object.keys(artifact.programs),known=new Set(lexicon.concepts.map(x=>x.id)),errors=[];
const missing=ids.filter(id=>!artifact.programs[id]),orphan=profileIds.filter(id=>!catalog.programs[id]),byLevel={};
for(const id of ids){const expected=catalog.programs[id],p=artifact.programs[id];byLevel[expected.level]=(byLevel[expected.level]||0)+1;if(!p)continue;if(p.canonicalProgramId!==id)errors.push(`${id}: canonicalProgramId mismatch`);if(p.academicLevel!==expected.level)errors.push(`${id}: academicLevel mismatch`);if(!p.provenance?.source||!p.provenance?.derivationMethod||!p.provenance?.confidenceBand)errors.push(`${id}: missing provenance`);if(Object.values(p.riasec||{}).length!==6||Object.values(p.riasec).some(x=>typeof x!=="number"||x<0||x>1))errors.push(`${id}: invalid RIASEC`);const traits=Object.values(p.traitWeights||{}).flatMap(x=>Object.keys(x||{}));if(!traits.length)errors.push(`${id}: all traits zero`);for(const trait of traits)if(!known.has(trait))errors.push(`${id}: unknown concept ${trait}`);if(!Array.isArray(p.occupationalMappings))errors.push(`${id}: invalid O*NET mappings`);}
errors.push(...missing.map(x=>`missing:${x}`),...orphan.map(x=>`orphan:${x}`));
const confidence=Object.values(artifact.programs).reduce((a,p)=>(a[p.provenance.confidenceBand]=(a[p.provenance.confidenceBand]||0)+1,a),{});
const report={catalogProgramCount:ids.length,profileProgramCount:profileIds.length,coveredProgramCount:ids.length-missing.length,missingProgramCount:missing.length,orphanProgramCount:orphan.length,coveragePercent:Math.round(((ids.length-missing.length)/ids.length)*10000)/100,byAcademicLevel:byLevel,confidenceBands:confidence,fieldFamilyFallbackCount:profileIds.filter(id=>artifact.programs[id].occupationalMappings.length===0).length,conceptCount:lexicon.concepts.length,errorCount:errors.length,errors};
console.log(JSON.stringify(report,null,2));if(errors.length)process.exitCode=1;
