import { readFileSync } from "node:fs";
const load=p=>JSON.parse(readFileSync(new URL(p,import.meta.url),"utf8")),catalog=load("../src/config/educativeProgramRelations.json"),artifact=load("../src/config/vocationalProgramProfiles.json"),lexicon=load("../src/config/vocationalConceptLexiconV2.json"),onet=load("../src/config/onetVocationalSnapshot.json"),crosswalk=load("../src/config/onetVocationalCrosswalkV2.json");
const ids=Object.keys(catalog.programs),pids=Object.keys(artifact.programs),known=new Set(lexicon.concepts.map(x=>x.id)),occupationIds=new Set(Object.keys(onet.occupations)),mappingLevels=new Set(["broad_field","narrow_field","detailed_field"]),errors=[];
const MANIFEST={
 bachillerato_bachillerato_bivalente_militarizado_con_formacion_en_seguridad_ciudadana:["security","103","1032"],
 licenciatura_medicina_veterinaria_y_zootecnia:["veterinary","084","0841"],licenciatura_psicologia:["psychology","0313","0313"],licenciatura_psicologia_clinica:["psychology","0313","0313"],
 tecnico_bachillerato_seguridad_e_higiene_y_proteccion_civil:["security","103","1032"],licenciatura_arquitectura:["architecture","073","0731"],licenciatura_nutricion:["health","091","091"],ingenieria_biomedica:["health","091","091"],
 bachillerato_bachillerato_bivalente_militarizado_con_formacion_en_ciberseguridad:["ict","061","061"]
};
const missing=ids.filter(id=>!artifact.programs[id]),orphan=pids.filter(id=>!catalog.programs[id]),levels={},confidence={},review={high:[],medium:[],low:[]},byRule={},ambiguous=[];
const usesSource=(profile,dimension,prefix=null)=>Object.values(profile.traitEvidence?.[dimension]||{}).flat().some(item=>!prefix||item.elementId.startsWith(prefix));
for(const id of ids){const source=catalog.programs[id],p=artifact.programs[id];levels[source.level]=(levels[source.level]||0)+1;if(!p)continue;
 if(p.canonicalProgramId!==id||p.academicLevel!==source.level)errors.push(`${id}: identity/level mismatch`);
 const c=p.classification||{},cmpe=c.cmpe2016?.fieldCode,isced=c.iscedF2013?.fieldCode;for(const [name,value] of [["CMPE",c.cmpe2016],["ISCED-F",c.iscedF2013]])if(!value?.fieldCode||!mappingLevels.has(value.mappingLevel))errors.push(`${id}: invalid ${name} classification`);const expectedIscedLevel=({2:"broad_field",3:"narrow_field",4:"detailed_field"})[String(isced||"").length];if(c.iscedF2013?.mappingLevel!==expectedIscedLevel)errors.push(`${id}: ISCED-F ${isced} must be ${expectedIscedLevel}`);
 if(!c.domainId||!c.derivationRule||!c.taxonomyConfidence)errors.push(`${id}: incomplete taxonomy provenance`);byRule[c.derivationRule]=(byRule[c.derivationRule]||0)+1;if((c.matchedRules||[]).length>1)ambiguous.push(id);
 const expected=MANIFEST[id];if(expected&&(c.domainId!==expected[0]||cmpe!==expected[1]||isced!==expected[2]))errors.push(`${id}: expected ${expected.join('/')}, got ${c.domainId}/${cmpe}/${isced}`);
 for(const key of ["subjects","activities","abilities","workStyles","contexts"]){const traits=p.traitWeights?.[key];if(!traits||!Object.keys(traits).length)errors.push(`${id}: empty ${key}`);for(const trait of Object.keys(traits||{}))if(!known.has(trait))errors.push(`${id}: unknown concept ${trait}`);if(p.traitDimensionSources?.[key]==="onet_crosswalk"&&!Object.keys(p.traitEvidence?.[key]||{}).length)errors.push(`${id}: O*NET ${key} lacks evidence`);}
 for(const mapping of p.occupationalMappings||[]){if(!occupationIds.has(mapping.onetSocCode))errors.push(`${id}: unknown O*NET ${mapping.onetSocCode}`);if(!["high","medium","low"].includes(mapping.mappingConfidence)||!mapping.mappingRationale||!mapping.mappingType)errors.push(`${id}: incomplete O*NET mapping metadata`);}
 if(!p.occupationalMappings?.length&&/O\*NET/.test(p.provenance?.sourceVersion||""))errors.push(`${id}: false O*NET provenance`);if(!p.provenance?.derivationMethod||!p.provenance?.confidenceBand)errors.push(`${id}: missing provenance`);
 for(const [conceptId,restriction] of Object.entries(p.contextRestrictions||{}))if(restriction.hardRestrictionEligible&&restriction.confidence!=="high")errors.push(`${id}: unsafe hard restriction ${conceptId}`);
 confidence[p.provenance.confidenceBand]=(confidence[p.provenance.confidenceBand]||0)+1;if(p.provenance.reviewStatus!=="mapped_with_external_occupational_data"||c.taxonomyConfidence==="low"||(c.matchedRules||[]).length>1)review[p.provenance.confidenceBand]?.push(id);
}
for(const [dimension,map] of Object.entries(crosswalk.dimensions))for(const [elementId,conceptIds] of Object.entries(map))for(const conceptId of conceptIds)if(!known.has(conceptId))errors.push(`crosswalk ${dimension}/${elementId}: unknown ${conceptId}`);
errors.push(...missing.map(x=>`missing:${x}`),...orphan.map(x=>`orphan:${x}`));const all=Object.values(artifact.programs),mapped=all.filter(p=>p.occupationalMappings.length),metric=(dimension,prefix)=>all.filter(p=>usesSource(p,dimension,prefix)).length;
const report={catalogProgramCount:ids.length,profileProgramCount:pids.length,coveredProgramCount:ids.length-missing.length,missingProgramCount:missing.length,orphanProgramCount:orphan.length,coveragePercent:Math.round((ids.length-missing.length)/ids.length*10000)/100,byAcademicLevel:levels,confidenceBands:confidence,programsWithOnetMappings:mapped.length,realOnetMappingCount:mapped.reduce((sum,p)=>sum+p.occupationalMappings.length,0),programsUsingOnetKnowledge:metric("subjects","2.C."),programsUsingOnetAbilities:metric("abilities","1.A."),programsUsingOnetSkills:metric("abilities","2.A."),programsUsingOnetActivities:metric("activities","4.A."),programsUsingOnetContexts:metric("contexts","4.C."),programsUsingOnetWorkStyles:metric("workStyles","1.D."),fallbackCount:all.length-mapped.length,taxonomyLowConfidenceCount:all.filter(p=>p.classification.taxonomyConfidence==="low").length,ambiguousTaxonomyRuleCount:ambiguous.length,classificationCountByRule:Object.fromEntries(Object.entries(byRule).sort(([a],[b])=>a.localeCompare(b))),ambiguousTaxonomyPrograms:ambiguous,programsRequiringExpertReview:review,errorCount:errors.length,errors};
console.log(JSON.stringify(report,null,2));if(errors.length)process.exitCode=1;
