import { readFileSync, writeFileSync } from "node:fs";
const root=new URL("../src/config/",import.meta.url),load=(n)=>JSON.parse(readFileSync(new URL(n,root),"utf8"));
const relations=load("educativeProgramRelations.json"),lexicon=load("vocationalConceptLexiconV2.json"),onet=load("onetVocationalSnapshot.json"),known=new Set(lexicon.concepts.map(x=>x.id));
const n=(s)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase(),w=(ids)=>Object.fromEntries(ids.filter(x=>known.has(x)).map((x,i)=>[x,Math.max(.55,1-i*.08)]));
const FIELD={general:["001","001"],education:["011","011"],arts:["021","021"],social:["031","031"],psychology:["0313","0313"],communication:["032","032"],business:["041","041"],law:["042","0421"],science:["051","051"],ict:["061","061"],engineering:["071","071"],architecture:["073","0731"],agriculture:["081","081"],veterinary:["084","0841"],health:["091","091"],services:["101","101"],security:["103","1032"],transport:["104","1041"]};
const DOMAINS={
 general:[["communication"],["learning_variety","organization"],["verbal_reasoning"],["adaptability","dependability"],["people_work"],[.3,.4,.35,.45,.4,.45]],
 education:[["psychology","human_behavior"],["teaching","communication"],["verbal_reasoning","listening"],["empathy","dependability"],["people_work"],[.1,.45,.35,.95,.35,.3]],
 psychology:[["psychology","human_behavior"],["listening","helping","research"],["verbal_reasoning","critical_thinking"],["empathy","attention_to_detail"],["people_work"],[.05,.7,.3,1,.25,.35]],
 social:[["human_behavior","politics"],["research","communication","helping"],["critical_thinking","verbal_reasoning"],["empathy","adaptability"],["people_work"],[.1,.65,.35,.75,.45,.35]],
 arts:[["art","design"],["drawing","creativity","writing"],["spatial_reasoning"],["attention_to_detail","adaptability"],["independent_work"],[.2,.3,1,.35,.3,.2]],
 communication:[["communication","writing"],["public_speaking","research"],["verbal_reasoning"],["initiative","adaptability"],["people_work"],[.1,.45,.85,.65,.65,.25]],
 business:[["business","finance","accounting"],["administration","negotiation","leadership","sales"],["problem_solving","verbal_reasoning"],["initiative","dependability"],["office_work","people_work"],[.1,.35,.15,.45,.95,.75]],
 law:[["law","politics"],["research","negotiation","public_speaking"],["critical_thinking","verbal_reasoning"],["attention_to_detail","stress_tolerance"],["people_work","office_work"],[.1,.6,.25,.55,.85,.55]],
 science:[["mathematics","statistics","physics","chemistry","biology"],["research","experimentation"],["critical_thinking","problem_solving"],["attention_to_detail","dependability"],["laboratory","data_work"],[.2,1,.2,.2,.15,.55]],
 ict:[["computing","mathematics","data"],["programming","problem_solving"],["critical_thinking"],["attention_to_detail","adaptability"],["data_work","independent_work"],[.35,.9,.2,.15,.3,.7]],
 engineering:[["mathematics","physics","technology"],["problem_solving","design","experimentation"],["spatial_reasoning","critical_thinking"],["precision","attention_to_detail"],["machines_work","teamwork"],[.8,.85,.25,.15,.35,.5]],
 architecture:[["architecture","mathematics"],["design","drawing","construction"],["spatial_reasoning","problem_solving"],["creativity","attention_to_detail"],["teamwork","field_outdoors"],[.6,.55,.9,.25,.45,.35]],
 agriculture:[["biology","environment"],["agriculture","research","care"],["problem_solving"],["dependability","adaptability"],["field_outdoors","animals"],[.8,.7,.15,.4,.3,.3]],
 veterinary:[["biology","chemistry","animals"],["care","research","helping"],["problem_solving","attention_to_detail"],["empathy","stress_tolerance"],["animals","blood_environment","hospital_clinic"],[.6,.85,.15,.75,.2,.4]],
 health:[["biology","chemistry","health"],["care","helping","research"],["problem_solving","attention_to_detail"],["empathy","stress_tolerance","dependability"],["hospital_clinic","blood_environment","people_work"],[.25,.85,.15,.9,.2,.45]],
 services:[["tourism","food"],["gastronomy","organization","communication"],["problem_solving"],["stress_tolerance","adaptability"],["people_work","teamwork"],[.45,.2,.55,.75,.7,.45]],
 security:[["law","politics"],["helping","organization","problem_solving"],["critical_thinking"],["stress_tolerance","dependability"],["field_outdoors","teamwork"],[.65,.45,.1,.65,.55,.6]],
 transport:[["logistics","technology"],["transport","organization","problem_solving"],["spatial_reasoning"],["attention_to_detail","dependability"],["machines_work","teamwork"],[.7,.35,.1,.35,.55,.65]]};
const RULES=[[/veterin|zootec/,"veterinary"],[/psicolog/,"psychology"],[/proteccion civil|seguridad|criminolog|criminalistic/,"security"],[/arquitect|diseno.*interior|urbanismo/,"architecture"],[/periodis|comunicacion|publicidad|medios/,"communication"],[/derecho|jurid/,"law"],[/economia|administra|contab|finanz|negocio|mercad|capital humano|comercio/,"business"],[/nutric|medicin|medico|ciruj|enfermer|odont|salud|fisioter|farmac|biomedic/,"health"],[/agron|agric|forest|acuic|agro/,"agriculture"],[/biotecn|biolog|ambient|ecolog|matematic|estadistic|fisic|quimic|ciencias/,"science"],[/software|comput|informat|sistemas|datos|ciber|tecnologias de la informacion/,"ict"],[/ingenier|mecatron|electron|mecanic|manufactur|industrial|automotriz|mantenimiento|robot|energia/,"engineering"],[/educa|pedagog|docen|ensenanza/,"education"],[/sociolog|trabajo social|politic|relaciones internacionales/,"social"],[/arte|musica|diseno|animacion|cine|moda|literatura|filosofia|historia|idioma|lengua/,"arts"],[/logistic|transporte/,"transport"],[/turis|gastronom|hotel|deporte/,"services"]];
const ONET=[[/veterin/,["29-1131.00"]],[/psicologia clinica|licenciatura_psicologia$/,["19-3033.00"]],[/arquitectura/,["17-1011.00"]],[/software|programacion|sistemas computacionales/,["15-1252.00"]],[/contab/,["13-2011.00"]],[/economia/,["19-3011.00"]],[/derecho/,["23-1011.00"]],[/nutric/,["29-1031.00"]],[/periodis/,["27-3023.00"]],[/agron|agric/,["17-2021.00","11-9013.00"]],[/ingenieria biomedica/,["17-2031.00"]],[/ingenieria civil/,["17-2051.00"]],[/logistic/,["13-1081.00","11-3071.00"]],[/finanz/,["11-3031.00"]],[/mercadotec|marketing/,["11-2021.00"]],[/administra/,["11-1021.00"]],[/gastronom/,["35-1011.00"]],[/turismo/,["41-3041.00"]]];
const profiles={};for(const id of Object.keys(relations.programs).sort()){const program=relations.programs[id],text=n(`${program.canonicalName} ${id}`),domainId=(RULES.find(([re])=>re.test(text))||[null,"general"])[1],d=DOMAINS[domainId],field=FIELD[domainId],codes=(ONET.find(([re])=>re.test(text))||[])[1]||[],occupations=codes.map(code=>onet.occupations[code]).filter(Boolean),riasec=occupations.length?Object.fromEntries(["R","I","A","S","E","C"].map(k=>[k,Math.round((occupations.reduce((sum,o)=>sum+(o.riasec[k]||0),0)/occupations.length)*10000)/10000])):Object.fromEntries(["R","I","A","S","E","C"].map((k,i)=>[k,d[5][i]]));profiles[id]={canonicalProgramId:id,academicLevel:program.level,classification:{cmpe2016:{fieldCode:field[0],mappingLevel:field[0].length>3?"detailed_field":"broad_field"},iscedF2013:{fieldCode:field[1],mappingLevel:field[1].length>3?"detailed_field":"broad_field"}},riasec,traitWeights:{subjects:w(d[0]),activities:w(d[1]),abilities:w(d[2]),workStyles:w(d[3]),contexts:w(d[4])},occupationalMappings:codes.map(code=>({onetSocCode:code,title:onet.occupations[code].title,mappingConfidence:codes.length===1?"high":"medium",sourceVersion:"O*NET 30.3"})),provenance:{source:codes.length?"O*NET 30.3 aggregated occupation profile plus Blue academic field mapping":"CMPE 2016 and ISCED-F 2013 field fallback; O*NET not used",sourceVersion:codes.length?"O*NET 30.3; CMPE 2016; ISCED-F 2013":"CMPE 2016; ISCED-F 2013",derivationMethod:codes.length?`explicit_program_to_onet_${codes.length===1?"single":"aggregate"}`:`explicit_${domainId}_field_fallback`,confidenceBand:codes.length===1?"high":codes.length>1?"medium":"low",reviewStatus:codes.length?"mapped_with_external_occupational_data":"requires_expert_review"}};}
writeFileSync(new URL("vocationalProgramProfiles.json",root),`${JSON.stringify({schemaVersion:2,sourceCatalogVersion:relations.version,sourceVersions:{cmpe:"2016",iscedF:"2013",onetSnapshot:onet.version},programs:profiles},null,2)}\n`,"utf8");console.log(`Generated ${Object.keys(profiles).length} profiles; ${Object.values(profiles).filter(p=>p.occupationalMappings.length).length} use O*NET.`);
