import prisma from "../config/prisma.js";
import { ApiError } from "../utils/ApiError.js";
import { CAREER_LABS, CAREER_LAB_VERSION, REFLECTION_VALUES, getCareerLab, publicLab } from "../config/careerLabDefinitions.js";
import { normalizeProgramText, resolveCanonicalProgram } from "./educativeProgramRelationsService.js";

const SCORE_KEYS = ["logic", "creativity", "analysis", "communication", "organization", "constraints", "observation", "decisionMaking", "spatialReasoning", "problemSolving", "curiosity"];
const forbidden = ["score", "scores", "effects", "skills", "result", "careerTags", "state", "nextStep", "labVersion"];
function assertBody(body, allowed) { if (!body || typeof body !== "object" || Object.keys(body).some((key) => !allowed.includes(key) || forbidden.includes(key))) throw new ApiError(400, "Accion no permitida"); }
function labOrFail(key) { const lab = getCareerLab(key); if (!lab) throw new ApiError(404, "Lab no encontrado"); return lab; }
function currentStep(attempt, lab) { return lab.steps[(attempt.state?.stepIndex) || 0] || null; }
function normalizeScores(raw, lab) { const result = {}; for (const key of lab.skills) result[key] = Math.min(100, Math.round(((raw[key] || 0) / (lab.steps.length * 3)) * 100)); return result; }
function present(attempt) { const lab = labOrFail(attempt.labKey); const activeStep = attempt.status === "active" ? currentStep(attempt, lab) : null; return { id: attempt.id, lab: publicLab(lab), status: attempt.status, revision: attempt.revision, progress: { completed: attempt.state?.stepIndex || 0, total: lab.steps.length }, currentStep: activeStep ? publicLab({ ...lab, steps: [activeStep] }).steps[0] : null, skillScores: attempt.status === "completed" ? attempt.skillScores : null, reflection: attempt.reflection || null, startedAt: attempt.startedAt, completedAt: attempt.completedAt } }
export function listLabs() { return CAREER_LABS.map(publicLab); }
export function getLab(key) { return publicLab(labOrFail(key)); }
export async function startAttempt(userId, body) { assertBody(body, ["labKey"]); const lab = labOrFail(body.labKey); const attempt = await prisma.careerLabAttempt.create({ data: { userId, labKey: lab.key, labVersion: lab.version, areaKey: lab.area, state: { stepIndex: 0 }, answers: [], skillScores: {}, status: "active" } }); return present(attempt); }
export async function listAttempts(userId) { return (await prisma.careerLabAttempt.findMany({ where: { userId }, orderBy: { updatedAt: "desc" } })).map(present); }
async function owned(userId, id) { const attempt = await prisma.careerLabAttempt.findFirst({ where: { id, userId } }); if (!attempt) throw new ApiError(404, "Intento no encontrado"); return attempt; }
export async function getAttempt(userId, id) { return present(await owned(userId, id)); }
export async function act(userId, id, body) { assertBody(body, ["attemptId", "stepId", "optionId", "revision"]); if (body.attemptId !== id || !Number.isInteger(body.revision)) throw new ApiError(400, "Intento o revision invalida"); const attempt = await owned(userId, id); if (attempt.status !== "active") throw new ApiError(409, "El intento ya termino"); if (attempt.revision !== body.revision) throw new ApiError(409, "El intento cambio; actualiza la pantalla"); const lab = labOrFail(attempt.labKey); if (attempt.labVersion !== lab.version) throw new ApiError(409, "Version del lab no disponible"); const step = currentStep(attempt, lab); if (!step || step.id !== body.stepId) throw new ApiError(400, "Paso invalido"); const option = step.options.find((item) => item.id === body.optionId); if (!option) throw new ApiError(400, "Opcion invalida"); const raw = { ...(attempt.state?.rawScores || {}) }; for (const [key, value] of Object.entries(option.scores)) { if (!SCORE_KEYS.includes(key)) throw new ApiError(500, "Definicion de score invalida"); raw[key] = (raw[key] || 0) + value; } const nextIndex = (attempt.state?.stepIndex || 0) + 1; const done = nextIndex >= lab.steps.length; const result = await prisma.careerLabAttempt.updateMany({ where: { id, userId, revision: body.revision, status: "active" }, data: { state: { stepIndex: nextIndex, rawScores: raw }, answers: [...(attempt.answers || []), { stepId: step.id, optionId: option.id }], skillScores: done ? normalizeScores(raw, lab) : {}, status: done ? "completed" : "active", completedAt: done ? new Date() : null, revision: { increment: 1 } } }); if (result.count !== 1) throw new ApiError(409, "El intento cambio; actualiza la pantalla"); return getAttempt(userId, id); }
export async function reflect(userId, id, body) { assertBody(body, ["attemptId", "reflection", "revision"]); if (body.attemptId !== id || !REFLECTION_VALUES.includes(body.reflection) || !Number.isInteger(body.revision)) throw new ApiError(400, "Reflexion invalida"); const attempt = await owned(userId, id); if (attempt.status !== "completed") throw new ApiError(409, "Completa el lab antes de reflexionar"); if (attempt.reflection) throw new ApiError(409, "La reflexion ya fue guardada"); const result = await prisma.careerLabAttempt.updateMany({ where: { id, userId, revision: body.revision, status: "completed", reflection: null }, data: { reflection: body.reflection, revision: { increment: 1 } } }); if (result.count !== 1) throw new ApiError(409, "El intento cambio; actualiza la pantalla"); return getAttempt(userId, id); }
async function catalogRows() { return prisma.$queryRaw`SELECT o.id offerId, o.name institutionName, o.redirect_url redirectUrl, c.id campusId, c.name campusName, cc.id careerId, cc.name careerName FROM tbl_educative_offer_campus_careers cc JOIN tbl_educative_offer_campuses c ON c.id=cc.ev_educative_offer_campus_id JOIN tbl_educative_offer o ON CAST(o.id AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_bin=CAST(c.ev_educative_offer_id AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_bin WHERE COALESCE(o.active,0)=1 AND COALESCE(c.active,0)=1 AND COALESCE(cc.active,0)=1 AND cc.name IS NOT NULL` }
export async function relatedCareers(userId, id) { const attempt = await owned(userId, id); if (attempt.status !== "completed") throw new ApiError(409, "Completa el lab primero"); const lab = labOrFail(attempt.labKey); const tags = lab.careerTags.map(normalizeProgramText); const rows = await catalogRows(); return rows.filter((row) => { const canonical = resolveCanonicalProgram(row.careerName); const text = normalizeProgramText(`${canonical?.canonicalName || row.careerName} ${canonical?.category || ""}`); return tags.some((tag) => text.includes(tag)); }).slice(0, 12).map((row) => ({ careerId: String(row.careerId), name: row.careerName, institution: row.institutionName, offerId: String(row.offerId), campusId: String(row.campusId), campus: row.campusName, redirectUrl: row.redirectUrl || null })); }
export async function profile(userId) { const attempts = await prisma.careerLabAttempt.findMany({ where: { userId, status: "completed" }, orderBy: { completedAt: "desc" } }); const sums = {}, counts = {}, curiosity = {}; for (const attempt of attempts) { for (const [key, score] of Object.entries(attempt.skillScores || {})) { sums[key] = (sums[key] || 0) + score; counts[key] = (counts[key] || 0) + 1; } if (attempt.reflection) { const value = REFLECTION_VALUES.indexOf(attempt.reflection); const item = curiosity[attempt.areaKey] || { total: 0, count: 0 }; item.total += value; item.count += 1; curiosity[attempt.areaKey] = item; } } return { version: CAREER_LAB_VERSION, completedLabs: attempts.length, areasExplored: [...new Set(attempts.map((a) => a.areaKey))], interactionMetrics: Object.fromEntries(Object.keys(sums).map((key) => [key, Math.round(sums[key] / counts[key])])), curiosityMap: Object.fromEntries(Object.entries(curiosity).map(([key, value]) => [key, Math.round((value.total / Math.max(1, value.count) / 4) * 100)])), recentExperiences: attempts.slice(0, 6).map(present) }; }
