import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { getAttempts, getLabs, getProfile, getRelatedCareers, saveReflection, sendAction, startLab } from "../api/careerLabApi";

const reflections = [["BORED", "😴 Me aburrió"], ["NEUTRAL", "😐 Me dio igual"], ["INTERESTED", "🤔 Me interesó"], ["LIKED", "😄 Me gustó"], ["WANT_MORE", "🤯 Quiero probar más"]];
const labels = { logic: "Lógica", creativity: "Creatividad", analysis: "Análisis", communication: "Comunicación", organization: "Organización", constraints: "Trabajo con restricciones", observation: "Observación", decisionMaking: "Toma de decisiones", spatialReasoning: "Razonamiento espacial", problemSolving: "Resolución de problemas", curiosity: "Curiosidad durante la actividad" };

export default function CareerLabPage() {
  const [labs, setLabs] = useState([]), [attempts, setAttempts] = useState([]), [profile, setProfile] = useState(null), [attempt, setAttempt] = useState(null), [careers, setCareers] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const refresh = async () => { const [l, a, p] = await Promise.all([getLabs(), getAttempts(), getProfile()]); setLabs(l); setAttempts(a); setProfile(p); };
  useEffect(() => { refresh().catch((e) => setError(e.response?.data?.message || "No se pudo cargar Career Lab")).finally(() => setLoading(false)); }, []);
  const latest = useMemo(() => Object.fromEntries([...attempts].reverse().map((item) => [item.lab.key, item])), [attempts]);
  const run = async (fn) => { setError(""); setLoading(true); try { const value = await fn(); setAttempt(value); if (value.status === "completed") setCareers(await getRelatedCareers(value.id)); await refresh(); } catch (e) { setError(e.response?.data?.message || "No se pudo completar la acción"); } finally { setLoading(false); } };
  if (loading && !labs.length) return <main className="career-page"><p className="career-state">Cargando experiencias...</p></main>;
  return <main className="career-page">
    <header className="career-header"><Link to="/chat">← Chat</Link><div><strong>🧪 Career Lab</strong><small>Prueba profesiones antes de elegirlas.</small></div><Link to="/modo-2032">🔮 Modo 2032</Link></header>
    {error && <p className="career-error" role="alert">{error}</p>}
    <section className="career-shell">
      {!attempt && <><div className="career-hero"><p className="eyebrow">Microexperiencias determinísticas</p><h1>Explora distintas formas de trabajar</h1><p>No es un test ni una recomendación. Observa cómo interactuaste y decide qué te dio curiosidad.</p></div>
      <div className="career-grid">{labs.map((lab) => { const saved = latest[lab.key]; return <article className="career-card" key={lab.key}><span className="career-icon">{lab.icon}</span><small>{lab.area.replace("_", " ")} · {lab.estimatedMinutes} min</small><h2>{lab.title}</h2><p>{lab.description}</p><b>{saved?.status === "completed" ? "Completado" : saved?.status === "active" ? "En progreso" : "No iniciado"}</b><button disabled={loading} onClick={() => saved ? run(async () => { if (saved.status === "completed") setCareers(await getRelatedCareers(saved.id)); return saved; }) : run(() => startLab(lab.key))}>{saved?.status === "completed" ? "Ver resultado" : saved?.status === "active" ? "Continuar experiencia" : "Comenzar experiencia"}</button></article>; })}</div>
      <Profile profile={profile} />{!attempts.length && <p className="career-empty">Aún no hay experiencias completadas.</p>}</>}
      {attempt?.status === "active" && <section className="career-activity"><button className="career-back" onClick={() => setAttempt(null)}>← Volver al laboratorio</button><small>Paso {attempt.progress.completed + 1} de {attempt.progress.total}</small><progress max={attempt.progress.total} value={attempt.progress.completed}/><h1>{attempt.lab.title}</h1><h2>{attempt.currentStep.prompt}</h2><div className="career-options">{attempt.currentStep.options.map((option) => <button key={option.id} disabled={loading} onClick={() => run(() => sendAction(attempt, attempt.currentStep.id, option.id))}>{option.label}</button>)}</div></section>}
      {attempt?.status === "completed" && <section className="career-result"><button className="career-back" onClick={() => setAttempt(null)}>← Volver al laboratorio</button><p className="eyebrow">Así interactuaste con estas actividades</p><h1>{attempt.lab.title}</h1><p>Estas métricas describen decisiones dentro de esta experiencia; no son porcentajes de talento.</p><Metrics values={attempt.skillScores}/>{!attempt.reflection ? <><h2>¿Cómo te sentiste?</h2><div className="career-reflections">{reflections.map(([value, label]) => <button key={value} onClick={() => run(() => saveReflection(attempt, value))}>{label}</button>)}</div></> : <p className="career-note">Tu curiosidad se guardó separada del desempeño.</p>}<h2>Carreras relacionadas con esta experiencia</h2>{careers.length ? <div className="career-related">{careers.map((item) => <article key={`${item.careerId}-${item.campusId}`}><strong>{item.name}</strong><span>{item.institution} · {item.campus}</span>{item.redirectUrl && <a href={item.redirectUrl} target="_blank" rel="noreferrer">Ver oferta</a>}</article>)}</div> : <p>No encontramos coincidencias activas en el catálogo real para estas etiquetas.</p>}<Link className="career-cta" to="/modo-2032">Explorar en Modo 2032</Link></section>}
    </section></main>;
}
function Metrics({ values = {} }) { return <div className="career-metrics">{Object.entries(values).map(([key, value]) => <div key={key}><span>{labels[key] || key}</span><progress max="100" value={value}/><strong>{value}</strong></div>)}</div>; }
function Profile({ profile }) { if (!profile) return null; return <section className="career-profile"><h2>Tu perfil de interacción</h2><div className="career-summary"><div><strong>{profile.completedLabs}</strong><span>Labs completados</span></div><div><strong>{profile.areasExplored.length}</strong><span>Áreas exploradas</span></div></div><Metrics values={profile.interactionMetrics}/><h3>Mapa de Curiosidad</h3><p>En las experiencias que has probado, mostraste mayor interés en:</p><Metrics values={profile.curiosityMap}/></section>; }
