import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { chooseOption, createSimulation, getInstitutions, getPrograms, getSimulation, getSimulations } from "../api/futureSimulatorApi";
import { useAuth } from "../hooks/useAuth";

const metricLabels = { energy: "Energía", resources: "Recursos", freeTime: "Tiempo libre", workload: "Carga", stress: "Estrés", experience: "Experiencia", professionalNetwork: "Red" };
export default function FutureSimulatorPage() {
  const [step, setStep] = useState("welcome"), [startingLevel, setStartingLevel] = useState(""), [programs, setPrograms] = useState([]), [pagination, setPagination] = useState(null), [selectedProgram, setSelectedProgram] = useState(null), [institutions, setInstitutions] = useState([]), [selection, setSelection] = useState(null), [setup, setSetup] = useState({ workMode: "no", livingSituation: "familia", priority: "tiempo" }), [simulation, setSimulation] = useState(null), [saved, setSaved] = useState([]), [query, setQuery] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const { user, logout } = useAuth(); const navigate = useNavigate();
  useEffect(() => { getSimulations().then(setSaved).catch(() => {}); }, []);
  async function loadPrograms(level, page = 1) { setBusy(true); setError(""); try { const data = await getPrograms({ startingLevel: level, query, page, pageSize: 20 }); setPrograms(data.items); setPagination(data.pagination); setStep("programs"); } catch (e) { setError(e.response?.data?.message || "No fue posible consultar la oferta."); } finally { setBusy(false); } }
  async function selectProgram(item) { setBusy(true); try { setSelectedProgram(item); const data = await getInstitutions(startingLevel, item.programId); setInstitutions(data); setStep("institutions"); } catch (e) { setError(e.response?.data?.message || "No fue posible consultar instituciones."); } finally { setBusy(false); } }
  async function start() { setBusy(true); try { const next = await createSimulation({ startingLevel, programId: selectedProgram.programId, offerId: selection.offerId, campusId: selection.campusId, setup }); setSimulation(next); setStep("simulation"); setSaved(await getSimulations()); } catch (e) { setError(e.response?.data?.message || "No fue posible iniciar la simulación."); } finally { setBusy(false); } }
  async function decide(optionId) { setBusy(true); try { const next = await chooseOption(simulation.id, simulation.currentEvent.id, optionId); setSimulation(next); if (next.status === "completed") setStep("result"); setSaved(await getSimulations()); } catch (e) { setError(e.response?.data?.message || "La decisión ya no está disponible."); } finally { setBusy(false); } }
  async function openSaved(item) { setBusy(true); setError(""); try { const next = await getSimulation(item.id); setSimulation(next); setStep(next.status === "completed" ? "result" : "simulation"); } catch (e) { setError(e.response?.data?.message || "No fue posible abrir la simulación guardada."); } finally { setBusy(false); } }
  function exit() { logout(); navigate("/login"); }
  return <main className="future-page"><header className="future-header"><Link to="/chat">← Volver a Blue</Link><div><strong>🔮 Modo 2032</strong><small>{user?.name}</small></div><button onClick={exit}>Salir</button></header>{error && <p className="future-error">{error}</p>}<section className="future-shell">
    {step === "welcome" && <><p className="eyebrow">Simulador de futuros</p><h1>Explora decisiones antes de tener que tomarlas.</h1><p>Modo 2032 es una simulación orientativa basada en decisiones hipotéticas. No predice tu desempeño académico, económico ni profesional.</p><div className="future-cards"><button onClick={() => { setStartingLevel("secundaria"); loadPrograms("secundaria"); }}>Estoy en secundaria <small>Explorar preparatoria</small></button><button onClick={() => { setStartingLevel("preparatoria"); loadPrograms("preparatoria"); }}>Estoy en preparatoria <small>Explorar universidad</small></button></div>{saved.length > 0 && <Saved items={saved} busy={busy} onOpen={openSaved} />}</>}
    {step === "programs" && <><button className="future-back" onClick={() => setStep("welcome")}>← Cambiar nivel</button><h1>Elige una opción real</h1><form onSubmit={(e) => { e.preventDefault(); loadPrograms(startingLevel, 1); }}><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar programa" /><button disabled={busy}>Buscar</button></form><div className="future-list">{programs.map((item) => <button key={item.programId} onClick={() => selectProgram(item)}><strong>{item.canonicalName}</strong><small>{item.institutionCount} instituciones con esta opción</small></button>)}</div>{pagination && <nav className="future-pagination" aria-label="Paginación de programas"><button disabled={busy || pagination.page <= 1} onClick={() => loadPrograms(startingLevel, pagination.page - 1)}>Anterior</button><span>Página {pagination.page} de {pagination.totalPages}</span><button disabled={busy || pagination.page >= pagination.totalPages} onClick={() => loadPrograms(startingLevel, pagination.page + 1)}>Siguiente</button></nav>}</>}
    {step === "institutions" && <><button className="future-back" onClick={() => setStep("programs")}>← Cambiar programa</button><h1>Instituciones que ofrecen {selectedProgram?.canonicalName}</h1><div className="future-list">{institutions.map((institution) => institution.campuses.map((campus) => <article key={campus.campusId}><strong>{institution.name}</strong><p>{campus.name}{campus.municipality ? ` · ${campus.municipality}` : ""}</p><small>{[campus.shift, campus.modality].filter(Boolean).join(" · ")}</small><div><button onClick={() => { setSelection({ offerId: institution.offerId, campusId: campus.campusId }); setStep("setup"); }}>Seleccionar</button>{institution.redirectUrl && <a href={institution.redirectUrl} target="_blank" rel="noreferrer">Abrir Fórum</a>}</div></article>))}</div></>}
    {step === "setup" && <><button className="future-back" onClick={() => setStep("institutions")}>← Cambiar institución</button><h1>Configura una hipótesis</h1><Setup label="¿Piensas trabajar mientras estudias?" value={setup.workMode} onChange={(workMode) => setSetup({ ...setup, workMode })} options={[["no", "No"], ["medio-tiempo", "Medio tiempo"], ["fines-semana", "Fines de semana"]]} /><Setup label="¿Cómo imaginas tu situación?" value={setup.livingSituation} onChange={(livingSituation) => setSetup({ ...setup, livingSituation })} options={[["familia", "Vivir con familia"], ["compartir", "Compartir vivienda"], ["independiente", "Independizarme"]]} /><Setup label="¿Qué te preocupa más?" value={setup.priority} onChange={(priority) => setSetup({ ...setup, priority })} options={[["tiempo", "Tiempo"], ["recursos", "Recursos"], ["carga", "Carga académica"], ["adaptacion", "Adaptación"], ["experiencia", "Experiencia"]]} /><button className="future-primary" disabled={busy} onClick={start}>Comenzar simulación</button></>}
    {step === "simulation" && <><p className="eyebrow">{simulation.currentEvent.stage}</p><h1>{simulation.currentEvent.title}</h1><p>{simulation.currentEvent.description}</p><Metrics metrics={simulation.metrics} /><div className="future-cards">{simulation.currentEvent.options.map((option) => <button disabled={busy} key={option.id} onClick={() => decide(option.id)}><strong>{option.label}</strong><small>{option.explanation}</small></button>)}</div></>}
    {step === "result" && <><p className="eyebrow">Resultado de la simulación</p><h1>Tu recorrido hipotético</h1><p>{simulation.result.summary}</p><Metrics metrics={simulation.metrics} /><p className="future-disclaimer">{simulation.result.disclaimer}</p><button className="future-primary" onClick={() => setStep("welcome")}>Probar otra carrera</button><Saved items={saved} busy={busy} onOpen={openSaved} /></>}
  </section></main>;
}
function Setup({ label, value, onChange, options }) { return <label className="future-field">{label}<select value={value} onChange={(e) => onChange(e.target.value)}>{options.map(([id, text]) => <option key={id} value={id}>{text}</option>)}</select></label>; }
function Metrics({ metrics }) { return <div className="future-metrics">{Object.entries(metrics || {}).map(([key, value]) => <div key={key}><small>{metricLabels[key] || key}</small><strong>{value}</strong><progress value={value} max="100" /></div>)}</div>; }
const savedStatusLabels = { active: "En curso", completed: "Completada" };
function savedDate(value) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Fecha no disponible" : new Intl.DateTimeFormat("es-MX", { dateStyle: "medium" }).format(date); }
function Saved({ items, busy, onOpen }) { return <section className="future-saved"><h2>Simulaciones guardadas</h2><div className="future-saved-list">{items.map((item) => { const actionLabel = item.status === "active" ? "Continuar" : item.status === "completed" ? "Ver resultado" : "No disponible"; return <article key={item.id} className="future-saved-card"><div><strong>{item.programName || "Programa no disponible"}</strong><p>{item.institutionName || "Institución no disponible"}{item.campusName ? ` · ${item.campusName}` : ""}</p><small>{savedStatusLabels[item.status] || "Estado no disponible"} · Actualizada el {savedDate(item.updatedAt || item.createdAt)}</small></div><button disabled={busy || !savedStatusLabels[item.status]} onClick={() => onOpen(item)}>{actionLabel}</button></article>; })}</div></section>; }
