export const CAREER_LAB_VERSION = 1;
export const REFLECTION_VALUES = Object.freeze(["BORED", "NEUTRAL", "INTERESTED", "LIKED", "WANT_MORE"]);

const step = (id, prompt, options) => ({ id, prompt, options: options.map(([id, label, scores]) => ({ id, label, scores })) });
export const CAREER_LABS = Object.freeze([
  { key: "technology_debugging", version: 1, icon: "🖥️", title: "Depura un sistema", subtitle: "Encuentra el punto de falla", area: "technology", estimatedMinutes: 6, description: "Escenario ficticio de diagnóstico lógico.", skills: ["logic", "analysis", "problemSolving"], careerTags: ["software", "computing", "programming", "data"], steps: [step("trace", "El login falla después de validar la contraseña. ¿Qué revisas primero?", [["server_log", "Respuesta del servidor", { analysis: 3, logic: 2 }], ["colors", "Colores de la pantalla", { analysis: 1 }], ["database", "Conexión y consulta a la BD", { logic: 3, problemSolving: 2 }]]), step("order", "Elige el siguiente paso para aislar la causa.", [["reproduce", "Reproducir y registrar entradas", { analysis: 3, problemSolving: 2 }], ["rewrite", "Reescribir todo", { problemSolving: 1 }]])] },
  { key: "visual_design", version: 1, icon: "🎨", title: "Organiza una campaña", subtitle: "Define jerarquía y audiencia", area: "design", estimatedMinutes: 5, description: "Campaña ficticia para una bebida.", skills: ["creativity", "communication", "constraints"], careerTags: ["design", "communication", "animation", "digital_design"], steps: [step("audience", "¿Qué defines antes de organizar el mensaje?", [["audience", "La audiencia y el objetivo", { communication: 3, constraints: 2 }], ["decoration", "Solo la decoración", { creativity: 2 }]]), step("hierarchy", "Hay espacio para tres elementos. ¿Cómo priorizas?", [["message", "Mensaje, beneficio y llamada a la acción", { communication: 3, constraints: 3 }], ["everything", "Reducir todo para que quepa", { creativity: 2, constraints: 1 }]])] },
  { key: "architecture_spatial", version: 1, icon: "🏗️", title: "Distribuye espacios", subtitle: "Organiza zonas con restricciones", area: "built_environment", estimatedMinutes: 7, description: "Terreno y familia completamente ficticios.", skills: ["spatialReasoning", "organization", "constraints", "analysis"], careerTags: ["architecture", "civil", "industrial_design"], steps: [step("zones", "La zona tranquila no debe colindar con la calle. ¿Dónde va?", [["rear", "Al fondo del terreno", { spatialReasoning: 3, constraints: 3 }], ["front", "Junto a la calle", { organization: 1 }]]), step("circulation", "¿Qué distribución reduce recorridos?", [["central", "Servicios al centro", { organization: 3, analysis: 2 }], ["corners", "Todo en esquinas opuestas", { spatialReasoning: 1 }]])] },
  { key: "science_investigation", version: 1, icon: "🔬", title: "Investiga evidencia", subtitle: "Contrasta datos y conclusiones", area: "science", estimatedMinutes: 6, description: "Experimento ficticio y educativo.", skills: ["analysis", "curiosity", "logic"], careerTags: ["science", "biology", "chemistry", "environment"], steps: [step("variable", "Dos plantas reciben distinta luz. ¿Cuál es la variable cambiada?", [["light", "Horas de luz", { analysis: 3, logic: 3 }], ["height", "Altura final", { analysis: 1 }]]), step("claim", "Una muestra creció más. ¿Qué conclusión es válida?", [["limited", "Describe este ensayo, sin generalizar", { logic: 3, curiosity: 2 }], ["always", "Siempre ocurrirá igual", { logic: 1 }]])] },
  { key: "business_resources", version: 1, icon: "📊", title: "Administra recursos", subtitle: "Decide con presupuesto limitado", area: "business", estimatedMinutes: 7, description: "Negocio y presupuesto ficticios.", skills: ["organization", "decisionMaking", "constraints", "analysis"], careerTags: ["administration", "finance", "marketing", "business"], steps: [step("budget", "Debes mantener inventario y atraer clientes. ¿Qué haces?", [["balanced", "Distribuir con mínimos por rubro", { organization: 3, constraints: 3 }], ["all_ads", "Usar todo en publicidad", { decisionMaking: 2 }]]), step("change", "Sube el costo del inventario. ¿Cómo reaccionas?", [["review", "Revisar prioridades y reserva", { analysis: 3, decisionMaking: 3 }], ["ignore", "Mantener el plan sin revisar", { organization: 1 }]])] },
  { key: "health_observation", version: 1, icon: "🩺", title: "Organiza observaciones", subtitle: "Prioriza información ficticia", area: "health", estimatedMinutes: 6, description: "Actividad educativa; no diagnostica ni indica tratamientos.", skills: ["observation", "communication", "analysis"], careerTags: ["health", "nursing", "nutrition", "physiotherapy"], steps: [step("record", "¿Qué registro comunica mejor una observación?", [["facts", "Hechos, hora y contexto sin diagnosticar", { observation: 3, communication: 3 }], ["guess", "Una causa supuesta", { analysis: 1 }]]), step("privacy", "¿Cómo compartes la ficha ficticia?", [["minimum", "Solo datos necesarios con el responsable", { communication: 3, analysis: 2 }], ["public", "Publicarla completa", { observation: 1 }]])] },
]);

export function getCareerLab(key) { return CAREER_LABS.find((lab) => lab.key === key) || null; }
export function publicLab(lab) { return { ...lab, steps: lab.steps.map((s) => ({ id: s.id, prompt: s.prompt, options: s.options.map(({ id, label }) => ({ id, label })) })) }; }
